### ISSUE TITLE
请问未来会支持模糊录入吗

### ISSUE THREAD

**Issue by Marciy** [Akegarasu/blive-queue#1]
尝试了一下似乎只能识别设定好的“排队”和“取消排队”，关键词加其他字或者词就不会被识别到
![QQ截图20220512082809](https://user-images.githubusercontent.com/69225653/167968535-b1b91d83-9f27-47cf-bf37-82868e265f0d.jpg)
未来更新版本会识别到带“排队”的关键词模糊录入吗？

**Comment by Akegarasu** [comment]
会

**Comment by Marciy** [comment]
了解了，谢谢。
