### ISSUE TITLE
4.0文件打开后网页还是3.2。排队不显示

### ISSUE THREAD

**Issue by MBU0I** [Akegarasu/blive-queue#6]
4.0文件打开后网页还是3.2。后台黑框框里显示了排队名单但是控制台上没有反应，导致添加到直播间以后也没有任何显示。

**Comment by MBU0I** [comment]
现在排队的时候还是显示已经在队列中，排队失败。直接后台黑框也不显示了。秋神救命

**Comment by Zihao520** [comment]
谷歌显示有病毒自动停止下载

**Comment by jkjkbox** [comment]
你重新下载下

**Comment by Zihao520** [comment]
好的~谢谢您~啾咪

**Comment by Akegarasu** [comment]
shift+f5强制刷新网页

**Comment by MBU0I** [comment]
强制刷新网页后，网页更新到了4.0，但是排队后只显示序号，昵称，uid，详细信息还是一片空白，点击删除以后出现的是删除失败，uid转换出错

**Comment by MBU0I** [comment]
我的意思是，每次都要重新刷新一次吗，很麻烦诶秋神

**Comment by Akegarasu** [comment]
已核实为bug

**Comment by Akegarasu** [comment]
已修复 更新后需要强制刷新一下
