### ISSUE TITLE
排队失效

### ISSUE THREAD

**Issue by shui9527** [Akegarasu/blive-queue#9]
2023.8.12
排队失效
感觉像抓取不到弹幕

**Comment by Akegarasu** [comment]
已修复

**Comment by jkjkbox** [comment]
> 已修复

9/6 无法获取弹幕进行排队
![image](https://github.com/Akegarasu/blive-queue/assets/67184119/03a708ec-cc45-4a09-82f5-7cb31a67ea29)
![image](https://github.com/Akegarasu/blive-queue/assets/67184119/47185918-6998-4980-892f-9806847a98bc)
